[package]
name = "five_clique_rs"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
rustc-hash = "1.1.0"
